[package]
name = "utils"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.44.0" }
starknet = ">=2.11.4"
tongo = { path = ".." }

[lib]
sierra = true
casm = true

[scripts]
deploy_local = "sncast --profile localnet script run --no-state-file deploy_local"

[[target.starknet-contract]]
build-external-contracts = [
    "tongo::main::Tongo"
]
