[sncast.localnet]
url = "http://127.0.0.1:5050"
accounts-file = "./localnet/accounts.json"
account = "localnet"

[sncast.localnet5151]
url = "http://127.0.0.1:5151"
accounts-file = "./localnet/accounts.json"
account = "localnet"
