[package]
name = "tongo"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
erc20 = { path = "./erc20" }
starknet = "2.11.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.44.0" }

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["erc20::ERC20Contract"]

[scripts]
test = "snforge test"

# Needed for compilation to declare and deploy with sncast scripts
[lib]
sierra = true
casm = true

