name: Release on Github and publish to npm
on:
  push:
    tags:
      # expected format: v<version> (example: v0.0.1)
    - 'sdk-v*'

permissions:
  contents: read

jobs:
  build:
    name: Build, Test and generate artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set-up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build she
        run: pnpm build
        working-directory: packages/she

      - name: Build sdk
        run: pnpm build
        working-directory: packages/tongo-sdk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .

  publish:
    name: Publish npm package on Github
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 10.4.1

      - name: Set-up Node
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: "https://registry.npmjs.org/"
          package-manager-cache: false

      - name: Update package.json version from tag
        env:
          TAG: ${{ github.ref_name }}
        run: |
          VERSION=${TAG#sdk-v}
          pnpm version $VERSION --no-git-tag-version
        working-directory: packages/tongo-sdk

      - name: Publish
        run: pnpm publish --access public --verbose --no-git-checks
        working-directory: packages/tongo-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
